# Generated by Django 4.2 on 2023-04-30 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_project_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='img',
        ),
    ]
