# Generated by Django 4.2 on 2023-05-04 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_remove_project_img'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ('-created',)},
        ),
    ]
