# Generated by Django 4.2.1 on 2023-06-06 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_alter_project_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='value',
        ),
    ]
